backend:
  name: github
  repo: giopunt/verified-views-poc

media_folder: static/assets
public_folder: assets

collections:
  - name: episode
    label: Episode
    folder: episodes
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: 'Release Date', widget: date }
      - { name: url, label: 'Podcast Link', widget: string }
      - { name: image, label: Image, widget: image }
      - { name: description, label: Description }